/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppDatenschutz {
    }
    interface AppFaq {
    }
    interface AppFooter {
    }
    interface AppHero {
    }
    interface AppHome {
    }
    interface AppHowto {
    }
    interface AppImpressum {
    }
    interface AppMenu {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppDatenschutzElement extends Components.AppDatenschutz, HTMLStencilElement {
    }
    var HTMLAppDatenschutzElement: {
        prototype: HTMLAppDatenschutzElement;
        new (): HTMLAppDatenschutzElement;
    };
    interface HTMLAppFaqElement extends Components.AppFaq, HTMLStencilElement {
    }
    var HTMLAppFaqElement: {
        prototype: HTMLAppFaqElement;
        new (): HTMLAppFaqElement;
    };
    interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {
    }
    var HTMLAppFooterElement: {
        prototype: HTMLAppFooterElement;
        new (): HTMLAppFooterElement;
    };
    interface HTMLAppHeroElement extends Components.AppHero, HTMLStencilElement {
    }
    var HTMLAppHeroElement: {
        prototype: HTMLAppHeroElement;
        new (): HTMLAppHeroElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppHowtoElement extends Components.AppHowto, HTMLStencilElement {
    }
    var HTMLAppHowtoElement: {
        prototype: HTMLAppHowtoElement;
        new (): HTMLAppHowtoElement;
    };
    interface HTMLAppImpressumElement extends Components.AppImpressum, HTMLStencilElement {
    }
    var HTMLAppImpressumElement: {
        prototype: HTMLAppImpressumElement;
        new (): HTMLAppImpressumElement;
    };
    interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {
    }
    var HTMLAppMenuElement: {
        prototype: HTMLAppMenuElement;
        new (): HTMLAppMenuElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-datenschutz": HTMLAppDatenschutzElement;
        "app-faq": HTMLAppFaqElement;
        "app-footer": HTMLAppFooterElement;
        "app-hero": HTMLAppHeroElement;
        "app-home": HTMLAppHomeElement;
        "app-howto": HTMLAppHowtoElement;
        "app-impressum": HTMLAppImpressumElement;
        "app-menu": HTMLAppMenuElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppDatenschutz {
    }
    interface AppFaq {
    }
    interface AppFooter {
    }
    interface AppHero {
    }
    interface AppHome {
    }
    interface AppHowto {
    }
    interface AppImpressum {
    }
    interface AppMenu {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-datenschutz": AppDatenschutz;
        "app-faq": AppFaq;
        "app-footer": AppFooter;
        "app-hero": AppHero;
        "app-home": AppHome;
        "app-howto": AppHowto;
        "app-impressum": AppImpressum;
        "app-menu": AppMenu;
        "app-profile": AppProfile;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-datenschutz": LocalJSX.AppDatenschutz & JSXBase.HTMLAttributes<HTMLAppDatenschutzElement>;
            "app-faq": LocalJSX.AppFaq & JSXBase.HTMLAttributes<HTMLAppFaqElement>;
            "app-footer": LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
            "app-hero": LocalJSX.AppHero & JSXBase.HTMLAttributes<HTMLAppHeroElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-howto": LocalJSX.AppHowto & JSXBase.HTMLAttributes<HTMLAppHowtoElement>;
            "app-impressum": LocalJSX.AppImpressum & JSXBase.HTMLAttributes<HTMLAppImpressumElement>;
            "app-menu": LocalJSX.AppMenu & JSXBase.HTMLAttributes<HTMLAppMenuElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
